CursoOnline.Web/Models/ErrorViewModel.cs
using System;

namespace CursoOnline.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CursoOnline.Web/Controllers/CursoController.cs
using System.Linq;
using CursoOnline.Dominio._Base.Services;
using CursoOnline.Dominio.Cursos;
using CursoOnline.Dominio.Cursos.DTO;
using CursoOnline.Web.Util;
using Microsoft.AspNetCore.Mvc;

namespace CursoOnline.Web.Controllers
{
    public class CursoController : Controller
    {
        private readonly ArmazenadorCurso _armazenadorCurso;
        private readonly IRepository<Curso> _cursoRepository;

        public CursoController(ArmazenadorCurso armazenadorCurso, IRepository<Curso> cursoRepository)
        {
            _armazenadorCurso = armazenadorCurso;
            _cursoRepository = cursoRepository;
        }

        public IActionResult Index()
        {
            var cursos = _cursoRepository.Consultar();

            if (cursos.Any())
            {
                var dtos = cursos.Select(x => new CursoDto {
                    Id = x.Id,
                    Nome = x.Nome,
                    CargaHoraria = x.CargaHoraria,
                    PublicoAlvo = x.PublicoAlvo.ToString(),
                    Valor = x.Valor
                });
                
                return View("Index", PaginatedList<CursoDto>.Create(dtos, Request));
            }

            return View("Index", PaginatedList<CursoDto>.Create(null, Request));
        }

        public IActionResult Novo()
        {
            return View("NovoOuEditar", new CursoDto());
        }

        [HttpPost]
        public IActionResult Salvar(CursoDto model)
        {
            _armazenadorCurso.Armazenar(model);

            return Ok();
        }

        public IActionResult Editar(int id)
        {
            var curso = _cursoRepository.ObterPorId(id);
            var dto = new CursoDto {
                Id = curso.Id,
                Nome = curso.Nome,
                Descricao = curso.Descricao,
                CargaHoraria = curso.CargaHoraria,
                Valor = curso.Valor
            };

            return View ("NovoOuEditar", dto);
        }
    }
}

CursoOnline.Web/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CursoOnline.Web.Models;

namespace CursoOnline.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CursoOnline.Web/Views/Curso/Index.cshtml
@using CursoOnline.Dominio.Cursos.DTO
@using CursoOnline.Web.Util
@model CursoOnline.Web.Util.PaginatedList<CursoDto>
@{
    ViewData["Title"] = "Cursos";
}

<div id="pad-wrapper">
    <div class="row">
        <div class="col-md-12">
            <a href="/Curso" class="btn">Voltar</a>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <a href="/Curso/Novo" class="btn btn-primary">Novo</a>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Carga Horária</th>
                        <th>Público Alvo</th>
                        <th>Valor</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @item.Nome
                            </td>
                            <td>
                                @item.CargaHoraria
                            </td>
                            <td>
                                @item.PublicoAlvo
                            </td>
                            <td>
                                @item.Valor
                            </td>
                            <td>
                                <a href="/Curso/Editar/@item.Id" class="btn">Editar</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>

            @{
                var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
                var nextDisabled = !Model.HasNextPage ? "disabled" : "";
            }

            <a asp-action="Index" asp-route-page="@(Model.PageIndex - 1)" class="btn btn-default @prevDisabled">Anterior</a>
            <a asp-action="Index" asp-route-page="@(Model.PageIndex + 1)" class="btn btn-default @nextDisabled">Próximo</a>
        </div>
    </div>
</div>

CursoOnline.Web/Views/Curso/NovoOuEditar.cshtml
@model CursoOnline.Dominio.Cursos.DTO.CursoDto
@{
    ViewData["Title"] = "Cursos";
}

<div id="pad-wrapper">
    <div class="row">
        <div class="col-md-12">
            <a href="/Curso" class="btn">Voltar</a>
        </div>
    </div>
    <div class="row header">
        <div class="col-md-1">
            <h3>Cursos</h3>
        </div>
    </div>
    <div class="row form-wrapper">
        <div class="col-md-12">
            <form id="form" class="form-horizontal" asp-action="Salvar" asp-controller="Curso" asp-anti-forgery
                data-ajax="true" data-ajax-method="POST" data-ajax-failure="formFail" data-ajax-success="window.location = '/Curso'">
                <input type="hidden" class="form-control" asp-for="Id">
                <div class="form-group">
                    <label class="col-md-2 control-label">Nome</label>
                    <div class="col-md-8">
                        <input type="text" class="form-control" asp-for="Nome">
                        <span asp-validation-for="Nome" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label">Descrição</label>
                    <div class="col-md-8">
                        <textarea type="text" class="form-control" asp-for="Descricao"></textarea>
                        <span asp-validation-for="Descricao" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label">Carga Horária</label>
                    <div class="col-md-2">
                        <input type="text" class="form-control" asp-for="CargaHoraria">
                        <span asp-validation-for="CargaHoraria" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label">Público</label>
                    <div class="col-md-2">
                        <select class="form-control" asp-for="PublicoAlvo">
                            <option value="Estudante">Estudante</option>
                            <option value="Universitário">Universitário</option>
                            <option value="Empregado">Empregado</option>
                            <option value="Empreendedor">Empreendedor</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label">Valor</label>
                    <div class="col-md-2">
                        <input class="form-control" asp-for="Valor">
                        <span asp-validation-for="Valor" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-8">
                        <a href="/Curso" class="btn">Salvar</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{
    <script src="/js/jquery.validate.min.js"></script>
    <script src="/js/jquery.validate.unobtrusive.js"></script>
    <script src="js/jquery.unobtrusive-ajax-min.js"></script>
    <script src="js/excecaoDominio.js"></script>
}

CursoOnline.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CursoOnline.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Curso Online</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stulesheet" href="~/css/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@ViewData["Title"]</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Curso" asp-action="Index">Curso</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Curso Online - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/toastr.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>